[versions]
agp-version = "8.2.0"
kotlin-version = "1.9.21"
ksp-version = "1.9.22-1.0.16"
core-ktx-version = "1.12.0"
lifecycle-runtime-ktx-version = "2.6.2"
activity-compose-version = "1.8.2"
compose-bom-version = "2023.10.01"
glide-version = "1.0.0-beta01"
decompose-version = "2.1.2"
mvikotlin-version = "3.2.1"
room-version = "2.6.1"
dagger-version = "2.48.1"
retrofit-version = "2.9.0"
material3-version = "1.1.2"

[libraries]
kotlin-android-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx-version" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx-version" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose-version" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom-version" }
glide-compose = { group = "com.github.bumptech.glide", name = "compose", version.ref = "glide-version" }
decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose-version" }
decompose-jetpack = { group = "com.arkivanov.decompose", name = "extensions-compose-jetpack", version.ref = "decompose-version" }
mvikotlin = { group = "com.arkivanov.mvikotlin", name = "mvikotlin", version.ref = "mvikotlin-version" }
mvikotlin-main = { group = "com.arkivanov.mvikotlin", name = "mvikotlin-main", version.ref = "mvikotlin-version" }
mvikotlin-coroutines = { group = "com.arkivanov.mvikotlin", name = "mvikotlin-extensions-coroutines", version.ref = "mvikotlin-version" }
mvikotlin-logging = { group = "com.arkivanov.mvikotlin", name = "mvikotlin-logging", version.ref = "mvikotlin-version" }
room-core = { group = "androidx.room", name = "room-ktx", version.ref = "room-version" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room-version" }
dagger-core = { group = "com.google.dagger", name = "dagger", version.ref = "dagger-version" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger-version" }
retorfit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit-version" }
retorfit-gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit-version" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3-version" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
icons = { group = "androidx.compose.material", name = "material-icons-extended" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp-version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-version" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin-version" }

[bundles]
decompose = ["decompose", "decompose-jetpack"]
mvikotlin = ["mvikotlin", "mvikotlin-main", "mvikotlin-coroutines", "mvikotlin-logging"]
retorfit = ["retorfit-core", "retorfit-gson-converter"]
compose-ui = ["ui", "ui-graphics", "ui-tooling-preview"]